version: '3.8'
services:
    nginx:
        build:
            context: images/nginx
            args:
                username: ${USERNAME}
                domain: ${DOMAIN}
        container_name: ${APPLICATION}_nginx
        ports:
            - 80:80
            - 443:443
        links:
            - php
        volumes:
            - app-data:/var/www/html
            - ${WP_CONTENT_PLUGINS_PATH}:/var/www/html/wp-content/plugins
            - ./images/nginx/conf/ssl/:/etc/nginx/ssl/
            - ./images/nginx/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./images/nginx/conf/applications/${APPLICATION}.conf:/etc/nginx/application.conf
            - ./images/nginx/conf/includes:/etc/nginx/includes
        networks:
            mynetwork:
                aliases:
                    - ${DOMAIN}

    php:
        build:
            context: images/php
            dockerfile: Dockerfile-${PHP_VERSION}
            args:
                username: ${USERNAME}
                host_os: ${HOST_OS}
        container_name: ${APPLICATION}_php
        links:
            - mysql
        volumes:
          - app-data:/var/www/html
          - ${WP_CONTENT_PLUGINS_PATH}:/var/www/html/wp-content/plugins
          - /private:/private #/tmp dir for mac
        networks:
            - mynetwork
        environment:
            - WP_CORE_DIR=/var/www/html
            - WP_TESTS_DIR=/var/www/html/tests
            - PHP_IDE_CONFIG="serverName=Docker"

    mysql:
        image: mysql:5.7
        restart: always
        container_name: ${APPLICATION}_mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
          - db-data:/var/lib/mysql:delegated
        networks:
            - mynetwork

    mailhog:
        image: mailhog/mailhog
        container_name: ${APPLICATION}_mailhog
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge

volumes:
  app-data:
  db-data: