FROM luiztucillo/php73

ARG username
ENV USERNAME=$username

RUN useradd -m $USERNAME \
    && chown -R $USERNAME:$USERNAME /var/www/html

RUN echo "user = $USERNAME" >> $PHP_CONFIG_PATH/fpm/php-fpm.conf \
    && echo "group = $USERNAME" >> $PHP_CONFIG_PATH/fpm/php-fpm.conf

# Make sure the volume mount point is empty
USER $USERNAME
RUN rm -rf /var/www/html/*
WORKDIR /var/www/html
