FROM phpdockerio/php56-fpm:latest

ENV PHP_CONFIG_PATH=/etc/php5
ENV PACKAGES="golang-go git php5-memcached php5-mysql php5-redis php5-gd php5-memcache php5-xdebug"
ENV PHPUNIT_URL="https://phar.phpunit.de/phpunit-5.phar"
ENV GLOBAL_PATH=/usr/local/bin

ARG app_path
ENV APP_PATH=$app_path

ARG username
ENV USERNAME=$username

# Fix debconf warnings upon build
ARG DEBIAN_FRONTEND=noninteractive

# Install selected extensions and other stuff
RUN apt-get update \
    && apt-get -y --no-install-recommends install $PACKAGES \
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

# Configure
COPY conf/php.ini $PHP_CONFIG_PATH/fpm/
COPY conf/php.ini $PHP_CONFIG_PATH//cli/
COPY conf/php-fpm.conf $PHP_CONFIG_PATH//fpm/

RUN mkdir -p $APP_PATH \
    && useradd -m $USERNAME \
    && chown -R $USERNAME:$USERNAME $APP_PATH

RUN echo "user = $USERNAME" >> $PHP_CONFIG_PATH/fpm/php-fpm.conf \
    && echo "group = $USERNAME" >> $PHP_CONFIG_PATH/fpm/php-fpm.conf

### Install sendmail for use with mailhog
ENV GOPATH /tmp
RUN cd /tmp \
    && go get github.com/mailhog/mhsendmail \
    && cd /tmp/src/github.com/mailhog/mhsendmail/ \
    && go build \
    && cp /tmp/src/github.com/mailhog/mhsendmail/mhsendmail /usr/local/bin

##COMPOSER
USER root
COPY --from=composer:latest /usr/bin/composer $GLOBAL_PATH/composer
RUN chown $USERNAME:$USERNAME $GLOBAL_PATH/composer \
    && chmod +x $GLOBAL_PATH/composer

#Install and configure N98
RUN curl https://files.magerun.net/n98-magerun.phar -o $GLOBAL_PATH/n98 \
    && chown $USERNAME:$USERNAME $GLOBAL_PATH/n98 \
    && chmod +x $GLOBAL_PATH/n98

#Install and configure PHPCS
RUN curl -L https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar -o $GLOBAL_PATH/phpcs \
    && chown $USERNAME:$USERNAME $GLOBAL_PATH/phpcs \
    && chmod +x $GLOBAL_PATH/phpcs

#Install PHPUnit
RUN curl -L $PHPUNIT_URL -o $GLOBAL_PATH/phpunit \
    && chown $USERNAME:$USERNAME $GLOBAL_PATH/phpunit \
    && chmod +x $GLOBAL_PATH/phpunit

# Make sure the volume mount point is empty
USER $USERNAME
RUN rm -rf /var/www/html/*
WORKDIR $APP_PATH
