FROM phpdockerio/php56-fpm:latest

ENV PHP_CONFIG_PATH=/etc/php5
ENV PACKAGES="golang-go git subversion mysql-client php5-memcached php5-intl php5-mysql php5-redis php5-gd php5-memcache php5-xdebug"
ENV PHPUNIT_URL="https://phar.phpunit.de/phpunit-5.phar"
ENV GLOBAL_PATH=/usr/local/bin

# Fix debconf warnings upon build
ARG DEBIAN_FRONTEND=noninteractive

# Install selected extensions and other stuff
# apt-get update could be slow, so i separate in specific cachable
RUN apt-get update
RUN apt-get -y --no-install-recommends install $PACKAGES \
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

# Configure
COPY conf/php.ini $PHP_CONFIG_PATH/fpm/
COPY conf/php.ini $PHP_CONFIG_PATH/cli/
COPY conf/php-fpm.conf $PHP_CONFIG_PATH/fpm/

### Install sendmail for use with mailhog
ENV GOPATH /tmp
RUN cd /tmp \
    && go get github.com/mailhog/mhsendmail \
    && cd /tmp/src/github.com/mailhog/mhsendmail/ \
    && go build \
    && cp /tmp/src/github.com/mailhog/mhsendmail/mhsendmail /usr/local/bin

#Install and configure PHPCS
RUN curl -L https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar -o $GLOBAL_PATH/phpcs \
    && chmod +x $GLOBAL_PATH/phpcs

#Install PHPUnit
RUN curl -L $PHPUNIT_URL -o $GLOBAL_PATH/phpunit.phar \
    && chmod +x $GLOBAL_PATH/phpunit.phar \
    && ln -sf $GLOBAL_PATH/phpunit.phar $GLOBAL_PATH/phpunit

RUN mkdir -p /var/www/html
RUN rm -rf /var/www/html/*
WORKDIR /var/www/html
