FROM phpdockerio/php74-fpm:latest

ENV PHP_CONFIG_PATH=/etc/php/7.4
ENV PACKAGES="vim golang-go git subversion mysql-client php-memcached php7.4-mysql php7.4-intl php-redis php-xdebug php7.4-bcmath php7.4-gd php7.4-soap"
ENV PHPUNIT_URL="https://phar.phpunit.de/phpunit-8.phar"
ENV GLOBAL_PATH=/usr/local/bin

# Fix debconf warnings upon build
ARG DEBIAN_FRONTEND=noninteractive

# Install selected extensions and other stuff
# apt-get update could be slow, so i separate in specific cachable
RUN apt-get update
RUN apt-get -y --no-install-recommends install $PACKAGES \
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

# Configure
COPY conf/php.ini $PHP_CONFIG_PATH/fpm/
COPY conf/php.ini $PHP_CONFIG_PATH/cli/
COPY conf/php-fpm.conf $PHP_CONFIG_PATH/fpm/

RUN mkdir -p /var/www/html

### Install sendmail for use with mailhog
ENV GOPATH /tmp
RUN cd /tmp \
    && go get github.com/mailhog/mhsendmail \
    && cd /tmp/src/github.com/mailhog/mhsendmail/ \
    && go build \
    && cp /tmp/src/github.com/mailhog/mhsendmail/mhsendmail /usr/local/bin

##COMPOSER
# Base image already have composer
RUN composer global require -vvv hirak/prestissimo

#Install and configure PHPCS
RUN curl -L https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar -o $GLOBAL_PATH/phpcs \
    && chmod +x $GLOBAL_PATH/phpcs

#Install PHPUnit
RUN curl -L $PHPUNIT_URL -o $GLOBAL_PATH/phpunit.phar \
    && chmod +x $GLOBAL_PATH/phpunit.phar \
    && ln -sf $GLOBAL_PATH/phpunit.phar $GLOBAL_PATH/phpunit

# Make sure the volume mount point is empty
RUN rm -rf /var/www/html/*
WORKDIR /var/www/html
